apiVersion: 1

contactPoints:
  - orgId: 1
    name: super-admin-email
    receivers:
      - uid: super_admin_email
        type: email
        disableResolveMessage: false
        settings:
          addresses: $GRAFANA_ALERT_EMAILS
          singleEmail: false
          subject: |
            {{ template "default.title" . }}
          message: |
            {{ template "default.message" . }}

  - orgId: 1
    name: super-admin-critical-email
    receivers:
      - uid: super_admin_critical_email
        type: email
        disableResolveMessage: false
        settings:
          addresses: $GRAFANA_ALERT_CRITICAL_EMAILS
          singleEmail: false
          subject: |
            {{ template "default.title" . }}
          message: |
            {{ template "default.message" . }}
